FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json turbo.json ./
COPY apps/web-storefront/package.json ./apps/web-storefront/
COPY packages/ ./packages/

RUN npm install --include=dev --legacy-peer-deps

EXPOSE 3000

CMD ["npm", "run", "dev", "--workspace=@welqo/web-storefront"]
